### ISSUE TITLE
添加环境出错

### ISSUE THREAD

**Issue by ceeeeeeeeeeeeeeeeb** [AuroraZiling/pipManager#14]
### 请检查以下事项

- [x] 我查找过相关的 Issue

### 问题描述

![Image](https://github.com/user-attachments/assets/d563a11b-8e2f-40a8-95f5-cfba5e01394f)

### 应用版本

0.1.0

### 崩溃记录或日志文件

12:44:56 [Information] (Thread: 1) Logging started 12:44:56 [Information] (Thread: 1) Language sets to Auto 12:44:56 [Information] (Thread: 1) 0 cache file(s) deleted 12:44:56 [Debug] (Thread: 1) Hosting starting 12:44:56 [Information] (Thread: 1) [MainWindow] No previous selected environment found 12:44:57 [Information] (Thread: 1) [Library] Initialized 12:44:57 [Information] (Thread: 1) Application started. Press Ctrl+C to shut down. 12:44:57 [Information] (Thread: 1) Hosting environment: "Production" 12:44:57 [Information] (Thread: 1) Content root path: "D:\AppPortable\pipmanager" 12:44:57 [Debug] (Thread: 1) Hosting started 12:44:59 [Information] (Thread: 1) [Environment] Initialized 12:45:00 [Information] (Thread: 1) [AddEnvironment] Initialized 12:45:00 [Information] (Thread: 9) [AddEnvironment] Pip list in environment variable refreshed 12:45:10 [Information] (Thread: 1) [AddEnvironment] python.exe found in D:\App2\py3125\python.exe

### 复现流程

打开软件  通过python.exe添加环境   提示添加环境出错

**Comment by AuroraZiling** [comment]
看一下python.exe所在文件夹，或者是目录结构

**Comment by ceeeeeeeeeeeeeeeeb** [comment]
> 看一下python.exe所在文件夹，或者是目录结构

![Image](https://github.com/user-attachments/assets/1465f4a2-3f46-420c-a7b4-9ee316a2eb12)

此外 我也装了其它几个python  都显示环境添加错误 ，下面这个是python的类似便携版  也无法添加
 ![Image](https://github.com/user-attachments/assets/3af3409d-492c-4092-854d-0717c4ff6239)

在两台电脑上都试了  无法添加

**Comment by AuroraZiling** [comment]
试一下最新版本

**Comment by ceeeeeeeeeeeeeeeeb** [comment]
> 试一下最新版本

可以了（下载的是带runtime的文件）
听我说，谢谢你，
